# Generated by Django 4.2.6 on 2023-11-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='total',
            new_name='id',
        ),
    ]
