# Generated by Django 4.2.6 on 2023-11-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_total_factura_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id_productos',
            new_name='id',
        ),
    ]
