# Generated by Django 4.2.6 on 2023-11-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_id_productos_productos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='fecha_pago',
            new_name='id',
        ),
    ]
