# Generated by Django 4.2.6 on 2023-11-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_fecha_pago_proveedores_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidas_fijas',
            old_name='nombre',
            new_name='id',
        ),
    ]
